# Generated by Django 4.1 on 2022-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_category_post_remove_author_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="kind",
            field=models.CharField(
                choices=[("NE", "Новость"), ("AR", "Статья")], max_length=255
            ),
        ),
    ]
